# Site settings
title: Codoks | Desenvolvimento mobile e web aliados à inovação.
email: contato@codoks.com
description: Somos uma empresa de software, focada em inovação com o uso de tecnologias móveis e web.
keywords: desenvolvimento, software, mobile, web, internet, coisas, inovação
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://preview.codoks.com" # the base hostname & protocol for your site
twitter_username: codoks.tec
github_username: codoks
ogdescription: Somos uma empresa de software, focada em inovação com o uso de tecnologias móveis e web.
ogtitle: Codoks | Desenvolvimento mobile e web aliados à inovação.
ogimage: /images/logo_base.png

# Build settings
markdown: kramdown

#Authors
authors:
  jltafarel:
    name: Jose Luiz Tafarel
    display_name: Tafarel
    bio: Tafarel é graduando em sistemas de informação pela Universidade Paranaense (UNIPAR) e confundador da Codoks. Tem experiência com Ruby on Rails e Android.
    gravatar: 6d422e42d26918052106c661cd19e9b7
    email: tafarel@codoks.com
    web: http://jtafarel.github.io
    twitter: jltafarel
    github: jltafarel
  lucas:
    name: Lucas Rafagnin
    display_name: Rafagnin
    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    email: jorgen@company.com
    web: http://company.com
    twitter: company
    github: jorgenm
